### ISSUE TITLE
events in month view should sort by start time

### ISSUE THREAD

**Issue by saschaben** [ilios/calendar#14]
currently it appears that events in month view are sorted by course as well as start time within each day block; this leads to events being out of time order in the visual stack.

Events should be sorted strictly by start time.

**Comment by stopfstedt** [comment]
couldn't quite figure it out (yet), this may be something in the elemental calendar.

anyhow, i've unassigned myself from this issue for now. don't want to hog it as i don't expect to be working on it anytime soon.
