### ISSUE TITLE
improve styles of sorted objectives lists in calendar event details 

### ISSUE THREAD

**Issue by stopfstedt** [ilios/calendar#172]
based on [sascha's feedback](https://github.com/ilios/frontend/pull/2729#issuecomment-290465216):

> let's spruce up the calendar display a bit: sort order objective display needs bullets, and the competency text (currently in smaller font following) should get a bold as well.

> a future iteration will have to give better context for the buttons, but we can deal with that post release.

**Comment by jrjohnson** [comment]
Fixed in #173
