### ISSUE TITLE
Tooltips still failing to unload

### ISSUE THREAD

**Issue by saschaben** [ilios/calendar#2]
when viewing a detail page:
![tooltip](https://cloud.githubusercontent.com/assets/1753431/10251859/9c1ac73a-68e8-11e5-9658-c31eb4237eaf.png)

**Comment by saschaben** [comment]
...and causes some "unusual" behavior like
![tooltip2](https://cloud.githubusercontent.com/assets/1753431/10252264/45bfba28-68eb-11e5-801e-6ce83da4a09a.png)

**Comment by dartajax** [comment]
It is still possible to get two of them to display at once.  

See my screen shot below.

![image](https://cloud.githubusercontent.com/assets/7493331/11486754/f3d3dae2-976f-11e5-949f-9a53e7dd399d.png)

However, this particular issue has been resolved.
