### ISSUE TITLE
update alert icon needs color set

### ISSUE THREAD

**Issue by saschaben** [ilios/calendar#34]
is displaying black; should be displaying red in all views.

**Comment by stopfstedt** [comment]
@saschaben icon shows up red for me in HEAD of master branch.

![selection_091](https://cloud.githubusercontent.com/assets/1410427/12691666/f5d7e9e8-c6a2-11e5-8a77-ac4072afad71.png)

where are you seeing the grey icon?

**Comment by jrjohnson** [comment]
Grey icon is in embeded calendar.  Style seems to be in both places, I'm investigating.
