### ISSUE TITLE
detail view shows alert icon all  the time

### ISSUE THREAD

**Issue by saschaben** [ilios/calendar#35]
icon does not appear to be selective --- just shows as a static value on all detail pages, reagrdless of update status. the bleow selection shows not updated in calenar views:.
![detailviewalert](https://cloud.githubusercontent.com/assets/1753431/12688312/3cac74ec-c68a-11e5-89aa-7c0bf7e298c3.png)

**Comment by jrjohnson** [comment]
Fixed in frontend and PR in embeded app.
