### ISSUE TITLE
calendar update alerts do not show for session changes

### ISSUE THREAD

**Issue by saschaben** [ilios/calendar#36]
looks like we are only testing for changes to offering "updated on" values. should be checking for session as well. As noted in the original ticket, alerts are triggered for changes to the following values:

- [ ] change to start time
- [ ] change to end time
- [ ] change to location
- [ ] change to instructor
- [ ] change to session objectives
- [ ] change to session learning materials
- [ ] change to session description

at the moment, only start/end time, location, and instructor

**Comment by stopfstedt** [comment]
requires backend changes.

**Comment by stopfstedt** [comment]
closed via ilios/ilios#1304
