### ISSUE TITLE
Offering display bug in week-view during summer/winter-time change period

### ISSUE THREAD

**Issue by stopfstedt** [ilios/calendar#58]
originally reported as https://github.com/ilios/frontend/issues/1873.

**Comment by saschaben** [comment]
Further detail (updating initial report in https://github.com/ilios/frontend/issues/1873):
- **Month view:** unaffected.
- **Week view:** creates an incorrect one hour offset for events on all days in the week where time change occurs, whether preceding or following the day of the change.
- **Day view:** creates an incorrect one hour offset for events on the day of the time change.

**Comment by saschaben** [comment]
N.B.: this bug will need to be addressed and pushed to production no later than **September 21, 2016**.

**Comment by saschaben** [comment]
no issue:
![monthview](https://cloud.githubusercontent.com/assets/1753431/16994402/12a5f8ee-4e5c-11e6-9152-beddd65ded47.png)

week view mismatch:
![weekview](https://cloud.githubusercontent.com/assets/1753431/16994409/1ac58724-4e5c-11e6-9261-1f90724736d8.png)

Day of Time Change mismatch:
![dayof](https://cloud.githubusercontent.com/assets/1753431/16994416/221a7aca-4e5c-11e6-997a-a111e90db491.png)

**Comment by jrjohnson** [comment]
Looks like the issue is caused by the doubling of the 1am hour on these dates.
<img width="449" alt="screen shot 2016-09-27 at 2 13 55 pm" src="https://cloud.githubusercontent.com/assets/349624/18892032/c6004232-84bc-11e6-8c9f-71c1b435f0b3.png">
